[build]
builder = "dockerfile"
dockerfile = "./Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:8000 --workers 4 --worker-class sync --max-requests 1000 --timeout 60 dejabrew.wsgi:application"
